- name: installing nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: NodeJS

- name: user roboshop setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: user-roboshop

- name: app Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup